#!/bin/sh

# A dmenu wrapper script for system functions.

# For non-systemd init systems.
case "$(readlink -f /sbin/init)" in
	*runit*) hib="sudo -A zzz" ;;
	*openrc*) reb="sudo -A openrc-shutdown -r"; shut="sudo -A openrc-shutdown -p" ;;
esac

cmds="\
🔒 lock		betterlockscreen -l dim --off 5
🚪 leave bspwm	bspc quit
♻ renew bspwm	bspc wm -r
🐻 hibernate	${hib:-systemctl hibernate}
🔃 reboot	${reb:-systemctl reboot}
🖥 shutdown	${shut:-systemctl poweroff}"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu)" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
